- menu_name: "Διδακτική"

- name: "required"
  url: "/required/"
  class: "services-contact"
  title: "Προαπαιτούμενα"

- name: "required"
  url: "/required/"
  class: "services-contact"
  title: "Προαπαιτούμενα"

- name: "required"
  url: "/required/"
  class: "services-contact"
  title: "Προαπαιτούμενα"

- name: "required"
  url: "/required/"
  class: "services-contact"
  title: "Προαπαιτούμενα"

- name: "required"
  url: "/required/"
  class: "services-contact"
  title: "Προαπαιτούμενα"
